"""empty message

Revision ID: 1ee23072edbb
Revises: 939ed383902b
Create Date: 2017-08-06 22:33:41.911796

"""

# revision identifiers, used by Alembic.
revision = '1ee23072edbb'
down_revision = '939ed383902b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordCounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=True),
    sa.Column('frequencyData', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wordCounts')
    # ### end Alembic commands ###
