"""empty message

Revision ID: 939ed383902b
Revises: 5e8e93c10ac8
Create Date: 2017-06-26 23:06:42.035325

"""

# revision identifiers, used by Alembic.
revision = '939ed383902b'
down_revision = '5e8e93c10ac8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('sentiment_score', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'sentiment_score')
    ### end Alembic commands ###
