"""empty message

Revision ID: 964c932b8bfc
Revises: 496f82d59294
Create Date: 2016-11-17 23:39:17.500410

"""

# revision identifiers, used by Alembic.
revision = '964c932b8bfc'
down_revision = '496f82d59294'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('latitude', sa.Float(precision=10, asdecimal=6), nullable=True))
    op.add_column('tweet', sa.Column('longitude', sa.Float(precision=10, asdecimal=6), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'longitude')
    op.drop_column('tweet', 'latitude')
    ### end Alembic commands ###
