"""empty message

Revision ID: dde01076e172
Revises: dbafac90c013
Create Date: 2016-10-23 12:38:12.686123

"""

# revision identifiers, used by Alembic.
revision = 'dde01076e172'
down_revision = 'dbafac90c013'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('retweet_count', sa.Integer(), nullable=True))
    op.add_column('tweet', sa.Column('retweet_text', sa.String(), nullable=True))
    op.add_column('tweet', sa.Column('source', sa.String(), nullable=True))
    op.add_column('tweet', sa.Column('source_user_id', sa.String(), nullable=True))
    op.add_column('tweet', sa.Column('source_user_screen_name', sa.String(), nullable=True))
    op.add_column('tweet', sa.Column('tweet_id', sa.String(), nullable=True))
    op.add_column('tweet', sa.Column('url_link', sa.String(), nullable=True))
    op.add_column('tweet', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('tweet', sa.Column('user_location', sa.String(), nullable=True))
    op.add_column('tweet', sa.Column('user_screen_name', sa.String(), nullable=True))
    op.drop_column('tweet', 'associated_user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('associated_user', sa.VARCHAR(), nullable=True))
    op.drop_column('tweet', 'user_screen_name')
    op.drop_column('tweet', 'user_location')
    op.drop_column('tweet', 'user_id')
    op.drop_column('tweet', 'url_link')
    op.drop_column('tweet', 'tweet_id')
    op.drop_column('tweet', 'source_user_screen_name')
    op.drop_column('tweet', 'source_user_id')
    op.drop_column('tweet', 'source')
    op.drop_column('tweet', 'retweet_text')
    op.drop_column('tweet', 'retweet_count')
    ### end Alembic commands ###
